# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.centralwidget.setFont(font)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("background: lightgray")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(19, 520, 771, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.left_btn.setFont(font)
        self.left_btn.setStyleSheet("background: lightgray;\n"
"padding: 5px;\n"
"border: 1px solid black;\n"
"border-radius: 5px;")
        self.left_btn.setObjectName("left_btn")
        self.horizontalLayout.addWidget(self.left_btn)
        self.right_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.right_btn.setFont(font)
        self.right_btn.setStyleSheet("background: lightgray;\n"
"padding: 5px;\n"
"border: 1px solid black;\n"
"border-radius: 5px;")
        self.right_btn.setObjectName("right_btn")
        self.horizontalLayout.addWidget(self.right_btn)
        self.mirror_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.mirror_btn.setFont(font)
        self.mirror_btn.setStyleSheet("background: lightgray;\n"
"padding: 5px;\n"
"border: 1px solid black;\n"
"border-radius: 5px;")
        self.mirror_btn.setObjectName("mirror_btn")
        self.horizontalLayout.addWidget(self.mirror_btn)
        self.sharp_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.sharp_btn.setFont(font)
        self.sharp_btn.setStyleSheet("background: lightgray;\n"
"padding: 5px;\n"
"border: 1px solid black;\n"
"border-radius: 5px;")
        self.sharp_btn.setObjectName("sharp_btn")
        self.horizontalLayout.addWidget(self.sharp_btn)
        self.bw_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.bw_btn.setFont(font)
        self.bw_btn.setStyleSheet("background: lightgray;\n"
"padding: 5px;\n"
"border: 1px solid black;\n"
"border-radius: 5px;")
        self.bw_btn.setObjectName("bw_btn")
        self.horizontalLayout.addWidget(self.bw_btn)
        self.files_list = QtWidgets.QListWidget(parent=self.centralwidget)
        self.files_list.setGeometry(QtCore.QRect(20, 50, 151, 461))
        self.files_list.setStyleSheet("border: 1px solid black;\n"
"\n"
"background: white;")
        self.files_list.setObjectName("files_list")
        self.choose_dir_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.choose_dir_btn.setGeometry(QtCore.QRect(20, 20, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.choose_dir_btn.setFont(font)
        self.choose_dir_btn.setStyleSheet("background: darkgrey;\n"
"border: 1px solid black;\n"
"border-radius: 5px;")
        self.choose_dir_btn.setObjectName("choose_dir_btn")
        self.image_lb = QtWidgets.QLabel(parent=self.centralwidget)
        self.image_lb.setGeometry(QtCore.QRect(190, 22, 591, 481))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.image_lb.setFont(font)
        self.image_lb.setStyleSheet("background-color: darkgrey;\n"
"border-radius: 15px;")
        self.image_lb.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.image_lb.setObjectName("image_lb")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.left_btn.setText(_translate("MainWindow", "Вліво"))
        self.right_btn.setText(_translate("MainWindow", "Вправо"))
        self.mirror_btn.setText(_translate("MainWindow", "Відзеркалити"))
        self.sharp_btn.setText(_translate("MainWindow", "Різкість"))
        self.bw_btn.setText(_translate("MainWindow", "Ч/Б"))
        self.choose_dir_btn.setText(_translate("MainWindow", "Папка"))
        self.image_lb.setText(_translate("MainWindow", "Картинка"))
